# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_users', models.ManyToManyField(related_name='trips', to='logreg.User')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='logreg.User')),
            ],
        ),
    ]
